# Generated by Django 5.2.3 on 2025-06-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gear_images/')),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.gearitem')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_weekday', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_weekend', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_days_required', models.PositiveIntegerField(default=1)),
                ('requires_prebooking', models.BooleanField(default=False)),
                ('gear_items', models.ManyToManyField(related_name='packages', to='catalog.gearitem')),
            ],
        ),
    ]
