# Generated by Django 5.2.3 on 2025-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_gearitemimage_rentalpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearitem',
            name='price_per_day',
        ),
    ]
