# Generated by Django 5.2.3 on 2025-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gearitem_deposit_rentalpackage_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpackage',
            name='deposit',
        ),
    ]
