# Generated by Django 5.2.3 on 2025-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_rentalpackage_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя контактного лица', max_length=100)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=20)),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('vk_group_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на группу ВКонтакте')),
            ],
        ),
    ]
